#
# Makefile
#
# Make file for application to test the PQueueChannel class
#
# Copyright (c) 2006 Derek J Smithies
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is jester, jitter tester.
#
# The Initial Developer of the Original Code is Derek J Smithies
#
# Contributor(s): ______________________________________.
#
# $Log: Makefile,v $
# Revision 1.2  2006/12/07 20:49:39  dereksmithies
# Add doxygen comments to this program.
# Add doxygen configure file.
#
# Revision 1.1  2006/12/07 08:46:17  dereksmithies
# Initial cut of code to test the operation of PQueueChannel class.
#
#
#

PROG		= queue
SOURCES		:= main.cxx precompile.cxx



include $(PTLIBDIR)/make/ptlib.mak


docs: 
	doxygen docs.cfg

