# Simple makefile for the wavfile test program.
#
# Copyright (c) 1993-1998 Equivalence Pty. Ltd.
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is Portable Windows Library.
#
# The Initial Developer of the Original Code is Equivalence Pty. Ltd.
#
# Portions are Copyright (C) 1993 Free Software Foundation, Inc.
# All Rights Reserved.
#
# Contributor(s): ______________________________________.
#
# $Log: Makefile,v $
# Revision 1.2  2005/08/18 00:24:50  dereksmithies
# Tidyup so compiles on linux, tidy up copyright headers, add cvs logging.
#
#
#

PROG	= wavfile
SOURCES	:= main.cxx 

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif
 
include $(PTLIBDIR)/make/ptlib.mak
 
# End of Makefile
