# Simple makefile for the local address program.
#
# $Log: Makefile,v $
# Revision 1.1  2005/03/10 09:19:00  dereksmithies
# Initial release of code to illustrate the reading of the machines external ip address and hostname
#
#
PROG    = local
SOURCES = local.cxx

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
