# Simple makefile for the serial example program.
#
# copyright 2005 Derek J Smithies
#
# $Log: Makefile,v $
# Revision 1.1  2005/03/10 09:21:46  dereksmithies
# Initial release of a program to illustrate the operation of the serial port.
#
#
#
PROG    = serial
SOURCES = serial.cxx

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
