#
# Makefile
#
# Makefile for ptimer
#
# Copyright (c) 2006 Indranet Technologies Ltd.
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is Portable Windows Library.
#
# The Initial Developer of the Original Code is Indranet Technologies Ltd.
#
# Contributor(s): ______________________________________.
#
# $Log: Makefile,v $
# Revision 1.1  2006/05/23 04:36:49  dereksmithies
# Initial release of a test program to examine the operation of PTimer.
#
#
#
#
#


PROG = ptimer
SOURCES := main.cxx precompile.cxx

include $(PTLIBDIR)/make/ptlib.mak
