'\" t
.\" Man page for openmcu
.\" SGM 16 Jul 2001
.\"
.TH openmcu 1 "6 March 2006"
.LO 1
.SH NAME
openmcu \- simple Multi Conference Unit using H.323
.SH SYNOPSIS
.B openmcu
[\fIoptions\fR]...
.SH DESCRIPTION
.PP
.B openmcu
is a simple Mutli Conference Unit using the H.323 protocol. It sets up a
H.323 listener process, and then waits for incoming connections. Whenever an
incoming connection is established, it adds that call to the specified
conference or to the default one if none is specified. You specify one on
your H.323 client when you call the OpenMCU server with address
"room_name@server_name", where room_name is the conference you want to join.

.B openmcu
runs as a daemon process and is controlled via a web interface. This 
is accessed by pointing a web browser at port 1420 on the host machine, i.e.
http://host:1420

.SH OPTIONS
.PP
.B openmcu
accepts only a few command line options that determine how the 
program is run. These options differ between the Unix and Windows versions
of the software. A list of all available options (regardless of the platform)
can be obtained by running the executable with no options.

Most options are available in both long and short versions.
The options available on the Unix version of the program are:

.TP
\fB\-v\fR, \fB\-\-version\fR
Display the version information

.TP
\fB\-x\fR
Run as a foreground process rather than a daemon. In this mode, no pid file
is created.

.TP
\fB\-d\fR, \fB\-\-daemon\fR
Run as a daemon, i.e. background process. In this mode, a text file will
be created containing the process ID in the directory specified by the
\-p option, or if that is not specified, in the directory defined by _PATH_VARRUN
(usually /var/run), or if that symbol is not defined, in the directory
containing the the executable. The log output will also be written to
the system log.

.TP
\fB\-c\fR, \fB\-\-console\fR      
Send output to the console rather than the system log

.TP
\fB\-i\fR, \fB\-\-ini\-file\fR \ffn\fR
Specify the name of the file that stores the program options. By default
this is ~/.pwlib_config/openmcu.ini

.TP
\fB\-p\fR, \fB\-\-pid\-file\fR \ffn\fR
Specify the name of the file that contains the PID when \-d specified.
By default, 
.B openmcu
automatically listens for incoming calls on all TCP/IP network interfaces
available on the host machine. This option is useful for running multiple
copies of
.B openmcu
on the same multi\-homed machine, or for ensuring that only calls from the
external, or internal, network will be received on a particular handset.

.TP
\fB\-k\fR
Kill a running instance of the program, using the PID in a previously
created pid file

.SH CONFIGURATION FILE
.PP
.B openmcu
options are stored in the configuration file, which is
.B ~/.pwlib_config/openmcu.ini
by default, or can be set using the \-i option.
This file can be edited directly, but the preferred method of configuration
is via the web interface. If the file is edited, the program must be stopped
before editing, and restarted after editing. 

.SH EXAMPLES
.PP

.TP
openmcu -xc
Start the program and run as a foreground process

.TP
openmcu -d
Start the program and run as a background daemon

.SH FILES
.PP
~/.pwlib_config/openmcu.ini

.SH BUGS
.P
None known

.SH "SEE ALSO"
None
