# Simple makefile for the hello world program

PROG    = SortedListTest
SOURCES = SortedListTest.cxx

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
