#
# Makefile
#
# Makefile for ipv6test
#
# Copyright (C) 2004 Post Increment
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is Portable Windows Library.
#
# The Initial Developer of the Original Code is Post Increment
#
# Contributor(s): ______________________________________.
#
# $Log: Makefile,v $
# Revision 1.1  2004/12/14 07:04:05  csoutheren
# Initial version
#
#
#


PROG = ipv6test
SOURCES := main.cxx precompile.cxx

include $(PTLIBDIR)/make/ptlib.mak
