# Simple makefile to illustrate  md5 operation.
#
#  Copyright 2005 Indranet Technologies Ltd
#
# $Log: Makefile,v $
# Revision 1.1  2005/03/02 21:50:02  dereksmithies
# Initial release of example code to calculate MD5 sums of a supplied string.
#
#
#
PROG    = md5
SOURCES = encrypt.cxx


ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
