#!/bin/bash

# Включить в настройках "Экспорт(named pipe)"
# Enable in settings "Export(named pipe)"
#
# Начало трансляции в сеть
# To start broadcasting network
# /opt/openmcu-ru/scripts/web_stream_start name_room
#
# Открыть, например vlc плеером
# Open for example vlc player
# http://ip-adress:8090/stream.asx
#

DIR_BIN="/opt/openmcu-ru/bin"
DIR_CONF="/opt/openmcu-ru/config"
DIR_PIPE="/opt/openmcu-ru/pipe"

export LD_LIBRARY_PATH="/opt/openmcu-ru/lib"

$DIR_BIN/ffserver -f $DIR_CONF/ffserver.conf &

$DIR_BIN/ffmpeg -y\
 -r 10 -s 4cif -f rawvideo -i $DIR_PIPE/video.$1\
 -ar 16000 -f s16le -i $DIR_PIPE/sound.$1\
 http://127.0.0.1:8090/feed.ffm

kill %1
